# Generated by Django 3.1.7 on 2021-04-23 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyName', models.CharField(max_length=100)),
                ('partySlogan', models.CharField(max_length=200)),
                ('partyObjective', models.CharField(max_length=300)),
                ('partyLeader', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Politicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('postName', models.CharField(max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registrations.politicalparty')),
            ],
        ),
    ]
