# Generated by Django 3.1.7 on 2021-04-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_politicalparty_politicians'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='registrations.politicians')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='registrations.useraccounts')),
            ],
        ),
        migrations.CreateModel(
            name='PartyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='registrations.politicalparty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='registrations.useraccounts')),
            ],
        ),
    ]
