# Generated by Django 3.1.7 on 2021-04-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_partyrating_politicianrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyrating',
            name='rating',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='politicianrating',
            name='rating',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='politicianrating',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='registrations.politicians'),
        ),
    ]
