# Generated by Django 3.1.7 on 2021-04-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20210423_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='partyRating',
            field=models.PositiveIntegerField(default='10'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='politicianRating',
            field=models.PositiveIntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='politicianrating',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='registrations.politicians'),
        ),
    ]
