# Generated by Django 3.1.7 on 2021-04-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20210423_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrating',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='registrations.politicalparty'),
        ),
        migrations.AlterField(
            model_name='partyrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='registrations.useraccounts', unique=True),
        ),
        migrations.AlterField(
            model_name='politicianrating',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='registrations.politicians'),
        ),
        migrations.AlterField(
            model_name='politicianrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='registrations.useraccounts', unique=True),
        ),
    ]
