# Generated by Django 3.1.7 on 2021-04-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_politicianwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianwork',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workRatings', to='registrations.politicians'),
        ),
        migrations.AlterField(
            model_name='politicianwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workUser', to='registrations.useraccounts'),
        ),
    ]
