# Generated by Django 3.1.7 on 2021-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20210423_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianwork',
            name='Totalrating',
            field=models.PositiveIntegerField(default='10'),
        ),
    ]
