# Generated by Django 3.1.7 on 2021-04-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_politicianwork_totalrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicianwork',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='politicianwork',
            name='user',
        ),
        migrations.AlterField(
            model_name='politicianwork',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='registrations.politicians'),
        ),
        migrations.CreateModel(
            name='PoliticianWorkRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default='0')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workRatings', to='registrations.politicians')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workUser', to='registrations.useraccounts')),
            ],
        ),
    ]
