# Generated by Django 3.1.7 on 2021-04-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20210423_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianworkrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workUser', to='registrations.useraccounts', unique=True),
        ),
    ]
